# Generated by Django 5.0.1 on 2024-06-07 19:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('The_Investor', '0008_merge_20240513_0013'),
        ('The_Investor', '0020_alter_investmentrequest_is_allowed'),
        ('The_Investor', '0024_remove_investmentrequest_total_investmentrequest'),
    ]

    operations = [
    ]
