# Generated by Django 5.0.1 on 2024-06-08 02:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('The_Investor', '0025_merge_20240607_2213'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='investorratingcomment',
            unique_together=set(),
        ),
    ]
