# Generated by Django 5.0.1 on 2024-06-08 18:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('The_Investor', '0026_alter_investorratingcomment_unique_together'),
        ('The_Owner', '0039_merge_20240607_2213'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='investorratingcomment',
            unique_together={('investor', 'project')},
        ),
    ]
