# Generated by Django 5.0.1 on 2024-06-10 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('The_Investor', '0028_report'),
    ]

    operations = [
        migrations.AddField(
            model_name='investmentrequest',
            name='is_project_rated',
            field=models.BooleanField(default=False),
        ),
    ]
