# Generated by Django 5.0.1 on 2024-06-10 02:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('The_Investor', '0029_investmentrequest_is_project_rated'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='investmentrequest',
            name='investor_identifier',
        ),
    ]
