# Generated by Django 5.0.1 on 2024-06-10 02:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('The_Investor', '0030_remove_investmentrequest_investor_identifier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investorratingcomment',
            name='rating',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
