# Generated by Django 5.0.1 on 2024-06-07 19:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('The_Owner', '0035_message_is_read'),
        ('The_Owner', '0038_alter_owner_address_alter_owner_photo'),
    ]

    operations = [
    ]
