# Generated by Django 5.0.1 on 2024-06-09 23:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Chat', '0023_alter_chat_investor_remove_owner_user_and_more'),
        ('FM', '0022_remove_promorequest_activation_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='financialmovement',
            name='feasibility_study_request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Chat.feasibilitystudyrequest'),
        ),
        migrations.AddField(
            model_name='financialreport',
            name='feasibility_study_requests',
            field=models.ManyToManyField(blank=True, related_name='financial_reports', to='Chat.feasibilitystudyrequest'),
        ),
        migrations.AddField(
            model_name='financialreport',
            name='feasibility_study_total_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
